# <div align=center>Numpy</div>   #

In [1]:
import numpy as np

### Print the Numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


### Create a null vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Create a null vector of size 10 but the fifth value is 1

In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49

In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Reverse a vector

In [6]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### Create a 3X3 matrix with values ranging from 0 to 8

In [7]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


### Create a 3X3 identity matrix

In [9]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Create a 3X3X3 array with random values

In [10]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.31668346 0.52733001 0.31788544]
  [0.81111188 0.63121891 0.45389247]
  [0.30144327 0.79432261 0.71401062]]

 [[0.76140173 0.18656515 0.79813185]
  [0.55908264 0.17251732 0.16438424]
  [0.55800425 0.41652382 0.3353785 ]]

 [[0.80333507 0.4706749  0.42950494]
  [0.85911993 0.90407129 0.50908382]
  [0.35271278 0.03932357 0.39614029]]]


### Create a random vector of size 30 and find the mean value 

In [11]:
Z = np.random.random((30))
m = Z.mean()
print(m)

0.4645011852950096


### Create a 10X10 array with random values and find the minimum and the maximum value

In [12]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.007920664057639248 0.9951453407160512


### Create a 2D array with 1 on the border and zero inside

In [13]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Create a 8X8 matrix and fill it with checkboard pattern

In [14]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Create a 5X5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
Z = np.diag(1 + np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Consider a (6,7,8) shape array. What is the index (x,y,z) of the 100th element?

In [16]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


### Create a checkerboard pattern 8X8 matrix with the use of tile function

In [17]:
Z = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Normalize a 5X5 random matrix

In [18]:
Z = np.random.random([5,5])
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.22079335 0.47650143 0.00366432 0.52593088 0.26577601]
 [0.35525837 0.8204223  0.79825526 0.20945713 1.        ]
 [0.27844533 0.         0.15883905 0.22284166 0.42797397]
 [0.50979715 0.04797325 0.01454979 0.68261993 0.2064493 ]
 [0.58129895 0.7723595  0.3029107  0.83827545 0.61988358]]


### Design a custom dtype that describes a color as four unsigned bytes (RGBA)

In [19]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-19-5432efe93e2f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


### Multiply a 5x3 matrix by a 3x2 matrix 

In [20]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### Given a 1D array. Negate all elements which are between 3 and 8 (in place)

In [21]:
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


### Find output of the code:

In [22]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


### Round away from zero a float array

In [23]:
Z = np.random.uniform(-10,+10,10)
print(np.trunc(Z + np.copysign(0.5, Z)))

[  9.   6.  -8.  -7.  -8.  -9.   9. -10.  -6.  10.]


### Extract the integer part of a random array using 5 different methods

In [24]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[6. 1. 0. 4. 5. 4. 1. 4. 1. 6.]
[6. 1. 0. 4. 5. 4. 1. 4. 1. 6.]
[6. 1. 0. 4. 5. 4. 1. 4. 1. 6.]
[6 1 0 4 5 4 1 4 1 6]
[6. 1. 0. 4. 5. 4. 1. 4. 1. 6.]


### Create a 5X5 matrix with row values ranging from 0 to 4

In [25]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### Create a generator function that generates 10 integers and use it to build an array

In [26]:
def generator():
    for x in range(10):
        yield x
Z = np.fromiter(generator(), dtype = float, count = -1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Create a vector of size 10 with values ranging from 0 to 1(both excluded)

In [27]:
Z = linspace(0, 1, 12, endpoint = True )[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### Create a random vector of size 10 and then sort it

In [28]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00610571 0.01197218 0.43480506 0.50038823 0.54391243 0.735748
 0.76298084 0.81826165 0.86438551 0.90196568]


### To sum a small array faster than np.sum

In [29]:
Z = np.arange(10)
np.add.reduce(Z)

45

### Consider two random array A and B. Ckeck if the equal 

In [30]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


### Make an array immutable(read only)

In [31]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

### Consider a random 10X2 matrix representing cartesian coordinates. Convert them to polar coordinates

In [32]:
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.78850253 1.21061491 0.07677496 0.16126156 1.18775372 1.14681765
 0.9072947  0.30439968 0.83801102 0.69478439]
[0.09169884 0.87034641 0.00378534 0.95540567 0.75859616 0.68864587
 0.60063809 0.66675246 0.07465111 0.27897576]


### Create a structured array with x and y coordinates covering the [0,1]X[0,1] area

In [33]:
Z = np.zeros((10,10), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

### Create a random vector of size 10 qnd replace the maximum value by 0

In [34]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.8056348  0.17175613 0.36533676 0.65612665 0.         0.48295473
 0.6521377  0.21285791 0.76639357 0.57294206]


### Given two arrays X and Y. Construct the Cauchy matrix C(Cij = 1/(xi-yj))

In [35]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


### Print the minimum and maximum representable value for each numpy scalar type

In [36]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### How to print all the values of an array

In [37]:
np.set_printoptions()
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

### How to find the closest value (to a given scalar) in an array

In [38]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z - v).argmin())
print(Z[index])

51


### Create a structured array representing a position (x,y) and a color (r,g,b)

In [39]:
Z = np.zeros(10, [('position', [('x', float, 1),
                                ('y', float, 1)]),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-39-15b802b0d590>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', [('x', float, 1),


### Cosider a random vector with shape (100,2) representing coordinates. Find point by point distances.

In [40]:
Z = np.random.random((10,2))
X, Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X - X.T)**2 + (Y - Y.T)**2 )
print(D)

[[0.         0.01730401 0.6576764  0.42522397 0.76399209 0.62007774
  0.82416469 0.63933216 0.9576806  0.59323185]
 [0.01730401 0.         0.67058131 0.41736974 0.76270333 0.60509997
  0.82817406 0.64208485 0.95221587 0.58370329]
 [0.6576764  0.67058131 0.         0.68978612 0.63755805 1.03446059
  0.47204715 0.43688945 0.92193387 0.82078394]
 [0.42522397 0.41736974 0.68978612 0.         0.40858734 0.34587631
  0.57435363 0.38996613 0.54207253 0.17623757]
 [0.76399209 0.76270333 0.63755805 0.40858734 0.         0.65619968
  0.25188259 0.20437667 0.28438744 0.37987021]
 [0.62007774 0.60509997 1.03446059 0.34587631 0.65619968 0.
  0.87618355 0.71114925 0.64143    0.276627  ]
 [0.82416469 0.82817406 0.47204715 0.57435363 0.25188259 0.87618355
  0.         0.19314029 0.50352637 0.60278796]
 [0.63933216 0.64208485 0.43688945 0.38996613 0.20437667 0.71114925
  0.19314029 0.         0.4874861  0.44880069]
 [0.9576806  0.95221587 0.92193387 0.54207253 0.28438744 0.64143
  0.50352637 0.4874861 

### How to convert a float array(32 bits) into an integer(32 bits) in place?

In [41]:
Z = np.arange(10, dtype = np.float32)
Z = Z.astype(np.int32, copy = False)
print(Z.dtype)

int32


### What is equiivalent of a enumerate for numpy arrays?

In [42]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

for index in np.ndindex(Z.shape):
    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### Generate a generic 2-D Gaussian-like array 

In [43]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D - mu)**2 / (2.0 * sigma**2) ))
print(G)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### How to randomly place p elements in a 2D array?

In [44]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Subtract the mean of each row of a matrix

In [45]:
X = np.random.rand(5,10)

Y = X - X.mean(axis = 1, keepdims = True)

print(Y)

[[ 0.36870121  0.26157479  0.12500924 -0.31665645 -0.43065612 -0.06472079
   0.33452257  0.26593152 -0.17864884 -0.36505713]
 [-0.22570742  0.22477252  0.04428066 -0.00362213 -0.21816959 -0.28407798
   0.44924651 -0.26085357  0.4540282  -0.17989719]
 [ 0.09914242  0.16837167 -0.19431451  0.1212783   0.15825252  0.04195814
  -0.31799922 -0.0315472   0.30175418 -0.3468963 ]
 [-0.36935975  0.02663169 -0.02479034  0.11328608 -0.22383755  0.37756282
   0.33363822 -0.47905325 -0.14389485  0.38981693]
 [-0.25863132  0.06373605 -0.28502101 -0.32701791  0.39484597 -0.03248334
   0.37433593 -0.25932709  0.10940863  0.22015409]]


### How to sort an array by the nth column?

In [46]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 3 5]
 [1 4 8]
 [7 1 6]]
[[7 1 6]
 [1 3 5]
 [1 4 8]]


### How to tell the nearest value from a given value in an array

In [47]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4456659232944079


### How to tell if a given 2D array has null columns 

In [48]:
Z = np.random.randint(0,3, (3,10))
print(Z)
print((~Z.any(axis = 0)).any())

[[2 2 2 1 0 2 0 0 0 0]
 [1 2 0 0 0 1 0 1 1 2]
 [2 1 0 2 2 0 1 0 1 1]]
False


### Create an array class that has a name attribute

In [49]:
class NamedArray(np.ndarray):
    
    def __new__(cls, array, name = "no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
    
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)


range_10


### Consider a given vector. How to add 1 to each element indexed by a second vector (Be careful with repeated indices)

In [50]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength = len(Z))
print(Z)

[1. 2. 3. 1. 5. 3. 3. 5. 5. 2.]


### How to accumulate elements of a vector(X) to an array (F) based on an index list(I)?

In [51]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### Considering a (w,h,3) image of (dtype = ubyte), compute the number of unique colors

In [52]:
w, h = 16, 16
I = np.random.randint(0.2, (h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
n = len(np.unique(F))
print(np.unique(F))

[3074]


### Considering a one-dimensional vector D, compute means of subsets of D using a vector S of same size describing subset indices?

In [53]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,1,100)
D_sums = np.bincount(S, weights = D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.51594258]


### How to get the diagonal of a dot product?

In [54]:
A = np.arange(6).reshape(3,2)
B = np.arange(6).reshape(2,3)

np.diag(np.dot(A, B))

array([ 3, 14, 33])

### Consider an array of dimension (5,5,3), multiply it with an array with dimensions (5,5)

In [55]:
A = np.ones((5,5,3))
B = 2 * np.ones((5,5))

print(A * B[:,:, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### How to swap two rows of an array?

In [56]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing of all the triangles

In [57]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis = 1),-1,axis = 1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis = 1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 12) ( 1, 79) ( 2, 86) ( 2, 95) (12, 64) (12, 79) (12, 87) (14, 24)
 (14, 83) (18, 43) (18, 82) (19, 27) (19, 64) (24, 83) (27, 64) (35, 56)
 (35, 96) (43, 82) (54, 57) (54, 97) (56, 96) (57, 97) (62, 71) (64, 87)
 (71, 71) (74, 85) (74, 95) (85, 95) (86, 95)]


### Given an array C that is a bincount, produce an array A such that np.bicount(A) == C

In [58]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


### How to calculate averages using a sliding window over an array?

In [59]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### Consider a one dimensional array Z, build a two dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[3],Z[2],Z[1])

In [60]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### How to negate a boolean, or to change the sign of a float inplace?


In [61]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out = Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out = Z)

array([-0.48516418,  0.11447944, -0.31426764,  0.66430881,  0.89739982,
        0.98461259, -0.91102404, -0.8069894 , -0.94985087, -0.13794585,
       -0.48919466,  0.85063045,  0.66131657,  0.83479793, -0.91799908,
        0.64774606,  0.89559881,  0.34332723,  0.66000824, -0.25484631,
        0.10663636, -0.44373567, -0.00691322, -0.95565176,  0.24694722,
        0.73190542, -0.070132  ,  0.72876273,  0.56313065, -0.41325053,
       -0.13542114,  0.7457686 , -0.1961177 , -0.33293473,  0.33471975,
       -0.56864709, -0.34905926,  0.53160718,  0.17493656, -0.37937926,
        0.25971777, -0.78243263, -0.8353233 , -0.9469505 , -0.99912689,
        0.07302257, -0.16677751, -0.27355562,  0.48516866, -0.09551207,
       -0.61099822, -0.17384294,  0.04287854, -0.16570704, -0.84161347,
       -0.21337806, -0.69301577,  0.72397689, -0.29613896,  0.70535954,
       -0.51542304, -0.30563094, -0.32784293,  0.05959429, -0.77626566,
        0.63458685, -0.48230922, -0.25728482,  0.6391272 ,  0.44

### Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [62]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.47900203  9.35362643 18.96714963  1.63151635  6.09398362  4.07570583
  5.22455838 13.22535148  7.7211593   3.73205909]


### Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [63]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.68487582  3.00481087  2.66736735  2.24358649  5.31258292  1.23135369
   2.51592372  1.59059458  0.94930495  5.02045686]
 [ 4.7507099   0.13172862  0.10315592  4.12405328  2.58484825  2.1521427
   1.62731371  3.55952449  2.04794559  2.62937508]
 [ 3.51641765  1.70588487  2.13034826  1.34263414  4.38386163  4.57017432
   2.37384566  0.86117204  0.68634297  4.87475651]
 [ 2.20935092  7.01214083  6.77742324  1.88067456  9.37825812  2.28789998
   0.09271587  2.54427421  4.88924761  9.15744199]
 [ 0.13198187  4.64886943  4.04737557  1.41321713  6.83074825  3.76683794
   3.65409504  0.6911493   2.70378305  6.25747405]
 [ 5.01353336 10.34408681 10.80063473  7.01477138 13.05517737  0.99278819
   6.63135208  7.55912493  7.89197918 13.50783363]
 [ 6.1589564  11.25309576 11.36686858  6.92012893 13.79828898  1.75998731
   4.58279418  7.54427062  8.95076965 13.89601172]
 [ 1.65437796  6.14848648  5.4944924   0.12576217  8.30769851  4.7865333
   3.33380464  0.61949876  4.21918915  7.66891756]
 [

### Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fillvalue when necessary)

In [64]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r] = Z[z]

print(Z)
print(R)

[[0 9 9 3 0 9 1 0 2 3]
 [7 6 8 1 3 7 5 4 3 3]
 [0 3 5 2 6 1 6 0 8 7]
 [3 1 4 9 1 4 1 2 3 4]
 [6 8 1 1 4 0 0 0 7 2]
 [4 6 5 1 2 1 8 1 2 0]
 [7 4 2 6 9 7 5 9 5 9]
 [7 7 8 7 5 8 9 5 3 8]
 [1 1 2 2 8 5 6 6 6 8]
 [1 4 3 8 7 1 4 5 1 1]]
[[0 0 0 0 0]
 [0 0 9 9 3]
 [0 7 6 8 1]
 [0 0 3 5 2]
 [0 3 1 4 9]]


<ipython-input-64-79134c150b40>:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


### Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [65]:
Z = np.arange(1,15,dtype=uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### Compute a matrix rank

In [66]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


### How to find the most frequent value in an array?


In [67]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


### Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [68]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 1 4]
   [1 4 0]
   [3 3 0]]

  [[1 4 3]
   [4 0 2]
   [3 0 4]]

  [[4 3 0]
   [0 2 0]
   [0 4 3]]

  [[3 0 1]
   [2 0 2]
   [4 3 4]]

  [[0 1 2]
   [0 2 3]
   [3 4 4]]

  [[1 2 1]
   [2 3 0]
   [4 4 3]]

  [[2 1 4]
   [3 0 1]
   [4 3 2]]

  [[1 4 3]
   [0 1 1]
   [3 2 1]]]


 [[[1 4 0]
   [3 3 0]
   [1 3 3]]

  [[4 0 2]
   [3 0 4]
   [3 3 3]]

  [[0 2 0]
   [0 4 3]
   [3 3 2]]

  [[2 0 2]
   [4 3 4]
   [3 2 1]]

  [[0 2 3]
   [3 4 4]
   [2 1 0]]

  [[2 3 0]
   [4 4 3]
   [1 0 3]]

  [[3 0 1]
   [4 3 2]
   [0 3 3]]

  [[0 1 1]
   [3 2 1]
   [3 3 4]]]


 [[[3 3 0]
   [1 3 3]
   [1 1 0]]

  [[3 0 4]
   [3 3 3]
   [1 0 4]]

  [[0 4 3]
   [3 3 2]
   [0 4 2]]

  [[4 3 4]
   [3 2 1]
   [4 2 3]]

  [[3 4 4]
   [2 1 0]
   [2 3 0]]

  [[4 4 3]
   [1 0 3]
   [3 0 0]]

  [[4 3 2]
   [0 3 3]
   [0 0 0]]

  [[3 2 1]
   [3 3 4]
   [0 0 1]]]


 [[[1 3 3]
   [1 1 0]
   [0 3 1]]

  [[3 3 3]
   [1 0 4]
   [3 1 3]]

  [[3 3 2]
   [0 4 2]
   [1 3 1]]

  [[3 2 1]
   [4 2 3]
   [3 1 0]]

  [[2 1 0]
   

### Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [69]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42

print(S)

[[ 8 10 13 10 10]
 [10  8 12 10 11]
 [13 12  7 42  3]
 [10 10 42  3 10]
 [10 11  3 10  0]]


### Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 

In [70]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


### Consider a 16x16 array, how to get the block­sum (block size is 4x4)?

In [71]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### How to implement the Game of Life using numpy arrays? 

In [72]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2: , 1:-1] + Z[2: , 2:])

    birth = (N == 3) & (Z[1:-1,1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### How to get the n largest values of an array?

In [73]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


### Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [74]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### How to create a record array from a regular array? 

In [75]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [76]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 7]


### Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [77]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[3 3 2]
 [3 2 0]
 [2 2 0]
 [1 4 4]
 [3 3 1]
 [0 2 2]
 [4 4 3]
 [2 0 0]
 [2 2 3]
 [1 3 0]]
[[3 3 2]
 [3 2 0]
 [2 2 0]
 [1 4 4]
 [3 3 1]
 [0 2 2]
 [4 4 3]
 [2 0 0]
 [2 2 3]
 [1 3 0]]


### Convert a vector of ints into a matrix binary representation

In [78]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### Given a two dimensional array, how to extract unique rows?

In [79]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1]))) 
_, idx = np.unique(T, return_index = True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


### Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [80]:
A = np.arange(0,10)
B = np.arange(0,10)

np.einsum('i->', A) 
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B) 
np.einsum('i,j', A, B) 

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

### Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [81]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)*2 + np.diff(y)*2) * 0.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x) 
y_int = np.interp(r_int, r, y)

### Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [82]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]
